spring:
  application:
    name: xxxservice	#用于指定注册到Eureka Server上的应用名称
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true	#表示将自己的IP注册到Eureka Server